### ISSUE TITLE
홈화면 카드 컴포넌트 생성

### ISSUE THREAD

**Issue by juniorcoma** [Splint-Final-Project/Pickle-Time-Frontend#26]
## 📌 기능설명
홈 화면의 피클 카드 컴포넌트 생성 입니다. 

![스크린샷 2024-06-03 224834](https://github.com/Splint-Final-Project/Pickle-Time-Frontend/assets/143431179/d81c3e82-c283-4197-bd71-98646052d403)

## 📌 ToDo
- [x] 인기 급상승 피클 카드 컴포넌트 생성
- [x] 전체 피클 카드 컴포넌트 생성 
- [x]  데이터 받아서 카드에 넣어주기

## 🤔 ETC[선택]
기타사항! (특별히 전달할 내용 or 질문 등등)
