### ISSUE TITLE
[피클 상세] 피클 상세 페이지 기능 구현

### ISSUE THREAD

**Issue by sihyonn** [Splint-Final-Project/Pickle-Time-Frontend#39]
## 📌 기능설명
피클 상세페이지 디자인이 나오기 전이라 들어갈 데이터 기능 구현 먼저 진행하도록 하겠습니다!

## 📌 ToDo
- [ ] 피클 상세 내용 표시
- [ ] 참여하기 버튼 클릭 시 결제창으로 넘어가도록
- [ ] 본인이 생성한 피클인 경우 참여하기 대신 수정하기 버튼 & 로직
- [ ] 찜버튼(개수포함), 1:1채팅버튼

## 🤔 ETC[선택]
기타사항! (특별히 전달할 내용 or 질문 등등)
